"""initial_agent_schema

Revision ID: 2f1fc3e1d858
Revises: 
Create Date: 2026-03-30 12:44:34.894947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f1fc3e1d858'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ceo', 'cto', 'engineer', 'researcher', 'reviewer', 'custom', name='agent_role'), nullable=False),
    sa.Column('adapter_type', sa.Enum('claude_local', 'codex_local', 'openai_assistants', 'http_webhook', name='adapter_type'), nullable=False),
    sa.Column('adapter_config', sa.JSON(), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('idle', 'running', 'paused', 'stopped', 'deactivated', name='agent_status'), nullable=False),
    sa.Column('chain_of_command', sa.JSON(), nullable=False),
    sa.Column('budget', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agents_company_id'), 'agents', ['company_id'], unique=False)
    op.create_table('agent_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('agent_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'completed', 'failed', 'cancelled', name='run_status'), nullable=False),
    sa.Column('trigger', sa.String(length=50), nullable=True),
    sa.Column('input_context', sa.JSON(), nullable=True),
    sa.Column('output', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_runs_agent_id'), 'agent_runs', ['agent_id'], unique=False)
    op.create_table('agent_skills',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('agent_id', sa.String(length=36), nullable=False),
    sa.Column('skill_id', sa.String(length=255), nullable=False),
    sa.Column('skill_version', sa.String(length=50), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_id', 'skill_id', name='uq_agent_skill')
    )
    op.create_index(op.f('ix_agent_skills_agent_id'), 'agent_skills', ['agent_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agent_skills_agent_id'), table_name='agent_skills')
    op.drop_table('agent_skills')
    op.drop_index(op.f('ix_agent_runs_agent_id'), table_name='agent_runs')
    op.drop_table('agent_runs')
    op.drop_index(op.f('ix_agents_company_id'), table_name='agents')
    op.drop_table('agents')
    # ### end Alembic commands ###
